'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Sultan_Turkish_Cuisine.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AlertDialogueOKbtnMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AlertDialogueOKbtnMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AlertDialogueOKbtnPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AlertDialogueOKbtnPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AlertDialogueOKbtnRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AlertDialogueOKbtnRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn0MouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn0MouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn0PNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn0PNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn0RolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn0RolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn10PoundMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn10PoundMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn10PoundPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn10PoundPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn10PoundRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn10PoundRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn1MouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn1MouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn1PNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn1PNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn1RolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn1RolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn2MouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn2MouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn2PNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn2PNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn2RolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn2RolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn30PoundMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn30PoundMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn30PoundPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn30PoundPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn30PoundRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn30PoundRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn3MouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn3MouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn3PNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn3PNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn3RolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn3RolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn4MouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn4MouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn4PNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn4PNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn4RolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn4RolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn50PoundMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn50PoundMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn50PoundPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn50PoundPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn50PoundRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn50PoundRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn5MouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn5MouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn5PNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn5PNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn5RolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn5RolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn6MouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn6MouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn6PNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn6PNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn6RolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn6RolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn7MouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn7MouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn7PNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn7PNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn7RolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn7RolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn8MouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn8MouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn8PNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn8PNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn8RolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn8RolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn9MouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn9MouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn9PNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn9PNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn9RolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn9RolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnBackSpaceMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnBackSpaceMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnBackSpacePNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnBackSpacePNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnBackSpaceRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnBackSpaceRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnCheckoutMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnCheckoutMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnCheckoutPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnCheckoutPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnCheckoutRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnCheckoutRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnClearAllMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnClearAllMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnClearAllPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnClearAllPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnClearAllRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnClearAllRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnClearMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnClearMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnClearPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnClearPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnClearRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnClearRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnDotMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnDotMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnDotPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnDotPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnDotRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnDotRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnExitMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnExitMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnExitPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnExitPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnExitRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnExitRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnHelpPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnHelpPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnINeedHelpMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnINeedHelpMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnINeedHelpPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnINeedHelpPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnINeedHelpRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnINeedHelpRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnLogOutMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnLogOutMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnLogOutPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnLogOutPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnLogOutRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnLogOutRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnPayMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnPayMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnPayPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnPayPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnPayRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnPayRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnRegisterMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnRegisterMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnRegisterPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnRegisterPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnRegisterRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnRegisterRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnWelcomeLoginMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnWelcomeLoginMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnWelcomeLoginRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnWelcomeLoginRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnWelcomeSignUpMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnWelcomeSignUpMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnWelcomeSignUpRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnWelcomeSignUpRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttonmousedown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonmousedown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttonrollover3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonrollover3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ChickenIskenderAddBtn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChickenIskenderAddBtn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ChickenIskenderAddBtnRollover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChickenIskenderAddBtnRollover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ChickenIskenderRemoveBtn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChickenIskenderRemoveBtn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ChickenIskenderRemoveBtnRollover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChickenIskenderRemoveBtnRollover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ChocolateCheesecakeAddBtn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChocolateCheesecakeAddBtn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ChocolateCheesecakeAddBtnRollover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChocolateCheesecakeAddBtnRollover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ChocolateCheesecakeRemoveBtn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChocolateCheesecakeRemoveBtn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ChocolateCheesecakeRemoveBtnRollover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChocolateCheesecakeRemoveBtnRollover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ConfirmLogOutbtnNoMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConfirmLogOutbtnNoMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ConfirmLogOutbtnNoPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConfirmLogOutbtnNoPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ConfirmLogOutbtnNoRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConfirmLogOutbtnNoRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ConfirmLogOutbtnYesMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConfirmLogOutbtnYesMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ConfirmLogOutbtnYesPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConfirmLogOutbtnYesPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ConfirmLogOutbtnYesRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConfirmLogOutbtnYesRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ErrorDialogueOKbtnMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ErrorDialogueOKbtnMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ErrorDialogueOKbtnPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ErrorDialogueOKbtnPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ErrorDialogueOKbtnRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ErrorDialogueOKbtnRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExitPanelPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExitPanelPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FAQbtnPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FAQbtnPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FAQClickedbtnPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FAQClickedbtnPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FAQContentPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FAQContentPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FAQMouseDownbtnPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FAQMouseDownbtnPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FAQRolloverbtnPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FAQRolloverbtnPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FrmbtnLoginPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FrmbtnLoginPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FrmbtnSignUpMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FrmbtnSignUpMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FrmbtnSignUpPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FrmbtnSignUpPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HelpClickedbtnPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HelpClickedbtnPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HelpFormbtnINeedHelpPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HelpFormbtnINeedHelpPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HelpFormbtnOrdersMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HelpFormbtnOrdersMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HelpFormbtnOrdersPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HelpFormbtnOrdersPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HelpFormbtnOrdersRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HelpFormbtnOrdersRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HelpMouseDownbtnPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HelpMouseDownbtnPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HelpRolloverbtnPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HelpRolloverbtnPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIClearAnOrderContentPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIClearAnOrderContentPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIClearAnOrderMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIClearAnOrderMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIClearAnOrderPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIClearAnOrderPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIClearAnOrderRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIClearAnOrderRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoICreateAnOrderContentPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoICreateAnOrderContentPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoICreateAnOrderMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoICreateAnOrderMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoICreateAnOrderPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoICreateAnOrderPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoICreateAnOrderRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoICreateAnOrderRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIExitTheApplicationContentPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIExitTheApplicationContentPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIExitTheApplicationMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIExitTheApplicationMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIExitTheApplicationPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIExitTheApplicationPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIExitTheApplicationRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIExitTheApplicationRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoILoginContentPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoILoginContentPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoILoginMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoILoginMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoILoginPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoILoginPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoILoginRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoILoginRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoILogOutContentPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoILogOutContentPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoILogoutMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoILogoutMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoILogoutPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoILogoutPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoILogoutRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoILogoutRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIPayForAnOrderContentPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIPayForAnOrderContentPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIPayForAnOrderMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIPayForAnOrderMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIPayForAnOrderPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIPayForAnOrderPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIPayForAnOrderRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIPayForAnOrderRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIPrintTheReceiptContentPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIPrintTheReceiptContentPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIPrintTheReceiptMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIPrintTheReceiptMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIPrintTheReceiptPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIPrintTheReceiptPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIPrintTheReceiptRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIPrintTheReceiptRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIRegisterContentPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIRegisterContentPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIRegisterMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIRegisterMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIRegisterPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIRegisterPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIRegisterRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIRegisterRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIRemoveAnItemContentPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIRemoveAnItemContentPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIRemoveAnItemMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIRemoveAnItemMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIRemoveAnItemPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIRemoveAnItemPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIRemoveAnItemRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIRemoveAnItemRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIViewTheReceiptContentPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIViewTheReceiptContentPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIViewTheReceiptMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIViewTheReceiptMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIViewTheReceiptPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIViewTheReceiptPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HowDoIViewTheReceiptRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HowDoIViewTheReceiptRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LambChopsAddBtn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LambChopsAddBtn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LambChopsAddBtnRollover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LambChopsAddBtnRollover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LambChopsRemoveBtn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LambChopsRemoveBtn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LambChopsRemoveBtnRollover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LambChopsRemoveBtnRollover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MenuButtonCreamPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuButtonCreamPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MixShishAddBtn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MixShishAddBtn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MixShishAddBtnRollover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MixShishAddBtnRollover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MixShishRemoveBtn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MixShishRemoveBtn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MixShishRemoveBtnRollover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MixShishRemoveBtnRollover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OrderFormbtnOrdersPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OrderFormbtnOrdersPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ReceiptLogoPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReceiptLogoPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SlidingPanelPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SlidingPanelPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StrawberryCheesecakeAddBtn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StrawberryCheesecakeAddBtn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StrawberryCheesecakeAddBtnRollover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StrawberryCheesecakeAddBtnRollover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StrawberryCheesecakeRemoveBtn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StrawberryCheesecakeRemoveBtn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StrawberryCheesecakeRemoveBtnRollover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StrawberryCheesecakeRemoveBtnRollover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StrawberryMojitoAddBtn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StrawberryMojitoAddBtn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StrawberryMojitoAddBtnRollover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StrawberryMojitoAddBtnRollover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StrawberryMojitoRemoveBtn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StrawberryMojitoRemoveBtn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StrawberryMojitoRemoveBtnRollover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StrawberryMojitoRemoveBtnRollover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SuccessDialogueBoxOKbtnMouseDownPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SuccessDialogueBoxOKbtnMouseDownPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SuccessDialogueBoxOKbtnPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SuccessDialogueBoxOKbtnPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SuccessDialogueBoxOKbtnRolloverPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SuccessDialogueBoxOKbtnRolloverPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property SultanIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("SultanIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TroubleshootingbtnPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TroubleshootingbtnPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TroubleshootingClickedbtnPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TroubleshootingClickedbtnPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TroubleshootingContentPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TroubleshootingContentPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TroubleshootingMouseDownbtnPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TroubleshootingMouseDownbtnPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TroubleshootingRolloverbtnPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TroubleshootingRolloverbtnPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurkishCoffeeAddBtn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurkishCoffeeAddBtn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurkishCoffeeAddBtnRollover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurkishCoffeeAddBtnRollover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurkishCoffeeRemoveBtn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurkishCoffeeRemoveBtn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurkishCoffeeRemoveBtnRollover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurkishCoffeeRemoveBtnRollover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurkishDelightAddBtn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurkishDelightAddBtn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurkishDelightAddBtnRollover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurkishDelightAddBtnRollover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurkishDelightRemoveBtn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurkishDelightRemoveBtn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurkishDelightRemoveBtnRollover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurkishDelightRemoveBtnRollover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurkishTeaAddBtn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurkishTeaAddBtn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurkishTeaAddBtnRollover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurkishTeaAddBtnRollover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurkishTeaRemoveBtn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurkishTeaRemoveBtn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurkishTeaRemoveBtnRollover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurkishTeaRemoveBtnRollover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WelcomeLogInPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WelcomeLogInPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WelcomeSignUpPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WelcomeSignUpPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
